# Generated by Django 5.0.6 on 2024-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expence',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='expence',
            name='receipt',
            field=models.ImageField(default=None, upload_to='files/receipt'),
        ),
    ]
