# Generated by Django 5.0.6 on 2024-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bugget',
        ),
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='expence',
            name='receipt',
        ),
    ]
