# Generated by Django 5.0.6 on 2024-05-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_category_bugget_remove_category_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='category',
        ),
    ]
