# Generated by Django 5.0.6 on 2024-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expence_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='category',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
